<?xml version="1.0" encoding="utf-8"?><Database Name="GiaSuBK" Class="DataClassesGiaSuBKDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=202.191.56.71;Initial Catalog=GiaSuBK;Persist Security Info=True;User ID=dungnt" SettingsObjectName="GiaSuBK.DAL.Properties.Settings" SettingsPropertyName="GiaSuBKConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DataCity" Member="DataCities">
    <Type Name="DataCity">
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CityCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DistrictCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Commune" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CommuneCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CommuneLevel" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserToken" Member="UserTokens">
    <Type Name="UserToken">
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TokenCode" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TimeCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DefaultValue" Member="DefaultValues">
    <Type Name="DefaultValue">
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TableValue" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ValueName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ValueName2" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GS_Class" Member="GS_Classes">
    <Type Name="GS_Class">
      <Column Name="ClassID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ReqParentID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NameParent" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="PhoneEmail" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Ward" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="StudentID" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="StudentName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PhoneStudent" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Apply" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NumberApply" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NameSupport" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Money" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MoneyStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FormTeach" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InfoMore" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NameSupports" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Subjects" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ValueClass" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AddressParent" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="Lessons" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TimeCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ParentCmt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StudentCmt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="GS_Class_GS_Lesson" Member="GS_Lessons" ThisKey="ClassID" OtherKey="ClassID" Type="GS_Lesson" />
      <Association Name="GS_ReqParent_GS_Class" Member="GS_ReqParent" ThisKey="ReqParentID" OtherKey="ReqParentID" Type="GS_ReqParent" IsForeignKey="true" />
      <Association Name="GS_Student_GS_Class" Member="GS_Student" ThisKey="StudentID" OtherKey="StudentID" Type="GS_Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GS_Course" Member="GS_Courses">
    <Type Name="GS_Course">
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClassID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StudentID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReqParentID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ParentID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TimeCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeModify" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Modifier" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GS_InviteStudent" Member="GS_InviteStudents">
    <Type Name="GS_InviteStudent">
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InviteID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StudentID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ReqParentID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ParentID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TimeCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Money" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MoneyStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TimeModify" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GS_Lesson" Member="GS_Lessons">
    <Type Name="GS_Lesson">
      <Column Name="LessonID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ClassID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="GS_Class_GS_Lesson" Member="GS_Class" ThisKey="ClassID" OtherKey="ClassID" Type="GS_Class" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GS_OrderStudent" Member="GS_OrderStudents">
    <Type Name="GS_OrderStudent">
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderStudentID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NameStudent" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PhoneEmail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(350)" CanBeNull="true" />
      <Column Name="StudentID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Perposes" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SubjectSupport" Type="System.String" DbType="NVarChar(350)" CanBeNull="true" />
      <Column Name="SkillSupport" Type="System.String" DbType="NVarChar(350)" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.String" DbType="NVarChar(350)" CanBeNull="true" />
      <Column Name="Supports" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TimeSupports" Type="System.String" DbType="NVarChar(350)" CanBeNull="true" />
      <Column Name="FormTeach" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Radius" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Latitude" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ward" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SexStudent" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InfoMore" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GS_Parent" Member="GS_Parents">
    <Type Name="GS_Parent">
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Childrents" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Apply" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Teaching" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Done" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NameParent" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GS_Post" Member="GS_Posts">
    <Type Name="GS_Post">
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GS_ReqParent" Member="GS_ReqParents">
    <Type Name="GS_ReqParent">
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReqParentID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ParentID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NameParent" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="PhoneEmail" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="AddressParent" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="FormTeach" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InfoMore" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NeedMore" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SexTeacher" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QuantityStudent" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SelectSchool" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ValueClass" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NameSupports" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Subjects" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TimeSupport" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SkillSupport" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Ward" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="TimeModify" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifierID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="GS_ReqParent_GS_Class" Member="GS_Classes" ThisKey="ReqParentID" OtherKey="ReqParentID" Type="GS_Class" />
    </Type>
  </Table>
  <Table Name="dbo.GS_ReqStudent" Member="GS_ReqStudents">
    <Type Name="GS_ReqStudent">
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StudentName" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="Radius" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FormTeach" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="InfoMore" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Need" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SexStudent" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="Perpose" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="NameSupports" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Subjects" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TimeSupport" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SkillSupport" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Ward" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TimeModify" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifierID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SelectSchool" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Achievement" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Experience" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ReqStudentID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.GS_Student" Member="GS_Students">
    <Type Name="GS_Student">
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentID" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="StudentName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Ward" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OtherEmail" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TypeHome" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CPA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GPA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Subjects" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FormTeach" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TimeSupport" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Experience" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Achievement" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Apply" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Teaching" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Done" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="InfoMore" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SexStudent" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="ParentComment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="GS_Student_GS_Class" Member="GS_Classes" ThisKey="StudentID" OtherKey="StudentID" Type="GS_Class" />
    </Type>
  </Table>
  <Table Name="dbo.GS_ZaloUserInfo" Member="GS_ZaloUserInfos">
    <Type Name="GS_ZaloUserInfo">
      <Column Name="TokenCode" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Avatar" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StudentID" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ZaloUserID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Sex" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserRole" Member="UserRoles">
    <Type Name="UserRole">
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Role" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetCommune" Method="GetCommune">
    <Parameter Name="City" Parameter="city" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="District" Parameter="district" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="GetCommuneResult">
      <Column Name="Commune" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.MAIL_StudentReceivedMoney" Method="MAIL_StudentReceivedMoney">
    <Parameter Name="StudentName" Parameter="studentName" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="StudentID" Parameter="studentID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="Area" Parameter="area" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="MotelType" Parameter="motelType" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="QuantityP" Parameter="quantityP" Type="System.Int32" DbType="Int" />
    <Parameter Name="PriceMax" Parameter="priceMax" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PrintMin" Parameter="printMin" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Require" Parameter="require" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="IsGroup" Parameter="isGroup" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="BillCode" Parameter="billCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Radius" Parameter="radius" Type="System.String" DbType="NVarChar(10)" />
  </Function>
  <Function Name="dbo.GetDistrict" Method="GetDistrict">
    <Parameter Name="City" Parameter="city" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="GetDistrictResult">
      <Column Name="District" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GS_GetClassLst" Method="GS_GetClassLst">
    <Parameter Name="PageNumber" Parameter="pageNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="RowspPage" Parameter="rowspPage" Type="System.Int32" DbType="Int" />
    <Parameter Name="Search" Parameter="search" Type="System.String" DbType="NVarChar(100)" />
    <ElementType Name="GS_GetClassLstResult">
      <Column Name="ClassID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ReqParentID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NameParent" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="PhoneEmail" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Ward" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="StudentID" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="StudentName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PhoneStudent" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Apply" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NumberApply" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NameSupport" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Money" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MoneyStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FormTeach" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InfoMore" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NameSupports" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Subjects" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ValueClass" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AddressParent" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="Lessons" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ParentCmt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StudentCmt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TotalRows" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GS_GetExcelStudentLst" Method="GS_GetExcelStudentLst">
    <Parameter Name="PageNumber" Parameter="pageNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="RowspPage" Parameter="rowspPage" Type="System.Int32" DbType="Int" />
    <Parameter Name="Search" Parameter="search" Type="System.String" DbType="NVarChar(100)" />
    <ElementType Name="GS_GetExcelStudentLstResult">
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StudentName" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="Radius" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FormTeach" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="InfoMore" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Need" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SexStudent" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="Perpose" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="NameSupports" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Subjects" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TimeSupport" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SkillSupport" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Ward" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TimeModify" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifierID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SelectSchool" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Achievement" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Experience" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ReqStudentID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TotalRows" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GS_GetFindingClassLst" Method="GS_GetFindingClassLst">
    <Parameter Name="PageNumber" Parameter="pageNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="RowspPage" Parameter="rowspPage" Type="System.Int32" DbType="Int" />
    <Parameter Name="Search" Parameter="search" Type="System.String" DbType="NVarChar(100)" />
    <ElementType Name="GS_GetFindingClassLstResult">
      <Column Name="ClassID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ReqParentID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NameParent" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="PhoneEmail" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Ward" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="StudentID" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="StudentName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PhoneStudent" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Apply" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NumberApply" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NameSupport" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Money" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MoneyStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FormTeach" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InfoMore" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NameSupports" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Subjects" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ValueClass" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AddressParent" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="Lessons" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ParentCmt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StudentCmt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TotalRows" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GS_GetLessonLst" Method="GS_GetLessonLst">
    <Parameter Name="Month" Parameter="month" Type="System.String" DbType="NVarChar(7)" />
    <Parameter Name="ClassID" Parameter="classID" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="GS_GetLessonLstResult">
      <Column Name="LessonID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClassID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TotalRows" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GS_GetParentLst" Method="GS_GetParentLst">
    <Parameter Name="PageNumber" Parameter="pageNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="RowspPage" Parameter="rowspPage" Type="System.Int32" DbType="Int" />
    <Parameter Name="Search" Parameter="search" Type="System.String" DbType="NVarChar(100)" />
    <ElementType Name="GS_GetParentLstResult">
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReqParentID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ParentID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NameParent" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="PhoneEmail" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="AddressParent" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="FormTeach" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InfoMore" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NeedMore" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SexTeacher" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QuantityStudent" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SelectSchool" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ValueClass" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NameSupports" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Subjects" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TimeSupport" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SkillSupport" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Ward" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="TimeModify" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifierID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TotalRows" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GS_GetStudentApplyClass" Method="GS_GetStudentApplyClass">
    <Parameter Name="ClassID" Parameter="classID" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="GS_GetStudentApplyClassResult">
      <Column Name="RowID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentID" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="StudentName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Ward" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OtherEmail" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TypeHome" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CPA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GPA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Subjects" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FormTeach" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TimeSupport" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Experience" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Achievement" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Apply" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Teaching" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Done" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="InfoMore" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SexStudent" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="ParentComment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="OrderID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GS_GetStudentByDistance" Method="GS_GetStudentByDistance">
    <Parameter Name="Distance" Parameter="distance" Type="System.Int32" DbType="Int" />
    <Parameter Name="Latitude" Parameter="latitude" Type="System.Decimal" DbType="Decimal(18,8)" />
    <Parameter Name="Longitude" Parameter="longitude" Type="System.Decimal" DbType="Decimal(18,8)" />
    <ElementType Name="GS_GetStudentByDistanceResult">
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="StudentName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Ward" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OtherEmail" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TypeHome" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CPA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GPA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Subjects" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FormTeach" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TimeSupport" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Experience" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Achievement" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Apply" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Teaching" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Done" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="InfoMore" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SexStudent" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="ParentComment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Distance" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GS_GetStudentByReqParentID" Method="GS_GetStudentByReqParentID">
    <Parameter Name="ReqParentID" Parameter="reqParentID" Type="System.String" DbType="NVarChar(50)" />
  </Function>
  <Function Name="dbo.GS_GetStudentLst" Method="GS_GetStudentLst">
    <Parameter Name="PageNumber" Parameter="pageNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="RowspPage" Parameter="rowspPage" Type="System.Int32" DbType="Int" />
    <Parameter Name="Search" Parameter="search" Type="System.String" DbType="NVarChar(100)" />
    <ElementType Name="GS_GetStudentLstResult">
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StudentName" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="Radius" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FormTeach" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="InfoMore" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Need" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SexStudent" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="Perpose" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="NameSupports" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Subjects" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TimeSupport" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SkillSupport" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Ward" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TimeModify" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifierID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SelectSchool" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Achievement" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Experience" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ReqStudentID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TotalRows" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GS_GetStudentLst2" Method="GS_GetStudentLst2">
    <Parameter Name="PageNumber" Parameter="pageNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="RowspPage" Parameter="rowspPage" Type="System.Int32" DbType="Int" />
    <Parameter Name="Search" Parameter="search" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="District" Parameter="district" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Ward" Parameter="ward" Type="System.String" DbType="NVarChar(100)" />
    <ElementType Name="GS_GetStudentLst2Result">
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StudentName" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="Radius" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FormTeach" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="InfoMore" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Need" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SexStudent" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="Perpose" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="NameSupports" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Subjects" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TimeSupport" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SkillSupport" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Ward" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TimeModify" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifierID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SelectSchool" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Achievement" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Experience" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ReqStudentID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TotalRows" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GS_GetStudentMotelResgisterLst" Method="GS_GetStudentMotelResgisterLst">
    <Parameter Name="PageNumber" Parameter="pageNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="RowspPage" Parameter="rowspPage" Type="System.Int32" DbType="Int" />
    <Parameter Name="Search" Parameter="search" Type="System.String" DbType="NVarChar(100)" />
  </Function>
  <Function Name="dbo.GS_SearchStudent" Method="GS_SearchStudent">
    <Parameter Name="StudentName" Parameter="studentName" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="MSSV" Parameter="mSSV" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Faculty" Parameter="faculty" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="PointCPA" Parameter="pointCPA" Type="System.Int32" DbType="Int" />
    <Parameter Name="PointGPA" Parameter="pointGPA" Type="System.Int32" DbType="Int" />
    <Parameter Name="Distance" Parameter="distance" Type="System.Int32" DbType="Int" />
    <Parameter Name="Latitude" Parameter="latitude" Type="System.Decimal" DbType="Decimal(18,8)" />
    <Parameter Name="Longitude" Parameter="longitude" Type="System.Decimal" DbType="Decimal(18,8)" />
    <ElementType Name="GS_SearchStudentResult">
      <Column Name="RowID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="StudentName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Ward" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OtherEmail" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TypeHome" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CPA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GPA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Subjects" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FormTeach" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TimeSupport" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Experience" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Achievement" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Apply" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Teaching" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Done" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="InfoMore" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SexStudent" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="ParentComment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Distance" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.MAIL_SendMailMotelSelected" Method="MAIL_SendMailMotelSelected">
    <Parameter Name="StudentReqID" Parameter="studentReqID" Type="System.Int32" DbType="Int" />
    <Parameter Name="NameStudent" Parameter="nameStudent" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="EmailStudent" Parameter="emailStudent" Type="System.String" DbType="NVarChar(250)" />
  </Function>
  <Function Name="dbo.MAIL_SendMailParentReq" Method="MAIL_SendMailParentReq">
    <Parameter Name="NameParent" Parameter="nameParent" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="ValueClass" Parameter="valueClass" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PhoneEmail" Parameter="phoneEmail" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="AddressParent" Parameter="addressParent" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="Subjects" Parameter="subjects" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="SkillSupport" Parameter="skillSupport" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="TimeSupport" Parameter="timeSupport" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="FormTeach" Parameter="formTeach" Type="System.String" DbType="NVarChar(50)" />
  </Function>
  <Function Name="dbo.MAIL_SendMailStudentApply" Method="MAIL_SendMailStudentApply">
    <Parameter Name="ReqParent" Parameter="reqParent" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="StudentID" Parameter="studentID" Type="System.String" DbType="NVarChar(50)" />
  </Function>
  <Function Name="dbo.MAIL_SendMailStudentReq" Method="MAIL_SendMailStudentReq">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="StudentID" Parameter="studentID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ValueClass" Parameter="valueClass" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PhoneEmail" Parameter="phoneEmail" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="Subjects" Parameter="subjects" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="SkillSupport" Parameter="skillSupport" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="TimeSupport" Parameter="timeSupport" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="FormTeach" Parameter="formTeach" Type="System.String" DbType="NVarChar(50)" />
  </Function>
  <Function Name="dbo.MAIL_StudentConfimMoney" Method="MAIL_StudentConfimMoney">
    <Parameter Name="StudentName" Parameter="studentName" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="StudentID" Parameter="studentID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="Area" Parameter="area" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="MotelType" Parameter="motelType" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="QuantityP" Parameter="quantityP" Type="System.Int32" DbType="Int" />
    <Parameter Name="PriceMax" Parameter="priceMax" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PrintMin" Parameter="printMin" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Require" Parameter="require" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="IsGroup" Parameter="isGroup" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="BillCode" Parameter="billCode" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Radius" Parameter="radius" Type="System.String" DbType="NVarChar(10)" />
  </Function>
</Database>